# **Numpy**
- Numeric Python
- Numerical python
- background data type--> array
- Indexing & Slicing supported
- Mutable in nature

In [1]:
data = [10,20,30,40]

In [2]:
# int float values
import numpy as np

In [3]:
a = np.array(data)
a

array([10, 20, 30, 40])

In [ ]:
# Q. List vs numpy array

In [4]:
# q. what is type of numpy array
type(a)

numpy.ndarray

In [5]:
# to generate an array with sequence of numbers
np.arange(10)  # stop

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2,11) # start,stop

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(3,21,2) # start,stop,step

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
a

array([10, 20, 30, 40])

In [9]:
a[::2]

array([10, 30])

In [10]:
# lets create an array with 24 numbers
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
# 2D- rows,columns
s = np.arange(24).reshape(4,6)
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
# Lets check the properties of an array
s.ndim

2

In [14]:
# count rows,columns
s.shape

(4, 6)

In [15]:
# count total elements
s.size

24

In [16]:
# check data type
s.dtype

dtype('int64')

In [ ]:
#int-->float-->complex-->object

In [23]:
np.array([1+4j,'2',3.])

array(['(1+4j)', '2', '3.0'], dtype='<U64')

In [24]:
# call some operations
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [26]:
# add all numbers
print(s.sum())

276


In [27]:
s.max()

np.int64(23)

In [28]:
s.min()

np.int64(0)

In [29]:
s.mean() # avg

np.float64(11.5)

https://numpy.org/doc/stable/user/index.html#user

In [30]:
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [31]:
d = np.array([[ 0,  1,  2,  3,],
       [ 6,  7,  8,  9, ],
       [12, 13, 14, 15, ],
       [18, 19, 20, 21,]])
d

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

In [34]:
# fetch diagonal elements
d.diagonal()

array([ 0,  7, 14, 21])

#  **Shape Manipulation**

In [36]:
s

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [39]:
s.shape

(4, 6)

In [38]:
# temp- reshape(row,column)
s.reshape(3,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [40]:
# permnt- resize(row,column)
s.resize(2,12)

In [41]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
# temp- using .T --> transpose() operation
# transpose means convert rows into columns and vice-versa
s.T

array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])

In [45]:
s

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [47]:
# row-wise addition
s.sum(axis=1)

array([ 66, 210])

In [48]:
# column-wise addition
s.sum(axis=0)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34])